version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "slackbot-wordle"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1omx5wp209o6r"
s3_prefix = "slackbot-wordle"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\""
image_repositories = []
