name: Deploy AWS SAM

on:
  workflow_dispatch: # Allow manual execution
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'src/**'

jobs:
  deploy:
    name: AWS SAM deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - run: sleep 5 # there's still a race condition for now (OIDC related)

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: aws-actions/setup-sam@v1

    - name: Configure AWS credentials
      run: |
        export AWS_ROLE_ARN=${{ secrets.OIDC_ROLE_AWS_ROLE_TO_ASSUME }}
        export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
        export AWS_DEFAULT_REGION=${{ secrets.OIDC_ROLE_AWS_REGION }}

        echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
        echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
        echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

    - name: Build SAM project
      run: |
        sam build

    - name: Run AWS SAM deploy
      run: |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
